[build]
  publish = "public"  # Make sure this is the correct directory where your XML files are stored
  command = "python update_rss.py"  # Adjust this if your script has a different name

[site]
  id = "2e673de3-8534-4e5f-bdfe-795fe51251db"  # Your Netlify Site ID

[[headers]]
  for = "/*.xml"
  [headers.values]
  Content-Type = "application/xml; charset=UTF-8"
