name: Update RSS Feed

on:
  schedule:
    - cron: "00 18 * * *"  # Runs at 12:00 PM CST (18:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: feature/rss-ui  # ✅ Ensures this runs on feature branch

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m pip install --upgrade pip  # Ensure latest pip version

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Debug GitHub Secrets
        run: |
          echo "Checking environment variables..."
          echo "NETLIFY_AUTH_TOKEN length: ${#NETLIFY_AUTH_TOKEN}"
          echo "NETLIFY_SITE_ID: ${NETLIFY_SITE_ID}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Verify Netlify Authentication
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          echo "Verifying Netlify Authentication..."
          netlify status || echo "⚠️ Netlify authentication failed!"

      - name: Link Netlify Site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          echo "Using Site ID: ${{ secrets.NETLIFY_SITE_ID }}"
          netlify link --id="${{ secrets.NETLIFY_SITE_ID }}"
          netlify status

      - name: Run RSS Update Script for Reiss
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: python update_rss.py  # ✅ This updates the Reiss RSS feed

      - name: Run RSS Update Script for Rav Asher Weiss
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: python update_rav_asher_weiss.py  # ✅ This updates Rav Weiss RSS feed

      - name: Upload Generated RSS Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RSS-Feeds
          path: deploy_netlify/

      - name: Verify Generated RSS Files
        run: ls -lh deploy_netlify/  # ✅ Lists generated files before deployment

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          echo "Deploying to Netlify..."
          netlify deploy --prod --dir="deploy_netlify" --debug
