name: Update RSS Feed

on:
  schedule:
    - cron: "00 18 * * *"  # Runs at 12:00 PM CST (18:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: feature/rss-ui  # ✅ Ensures workflow runs on the correct branch
          fetch-depth: 1  # Only fetch latest commit for speed

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Ensure Netlify is Linked
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          echo "🔗 Checking Netlify status..."
          netlify status || echo "⚠️ Netlify not linked, linking now..."
          netlify link --id="${{ secrets.NETLIFY_SITE_ID }}" || echo "✅ Netlify already linked."

      - name: Run RSS Update Script
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: python update_rss.py

      - name: Upload Generated RSS Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RSS-Feed
          path: deploy_netlify/

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir="deploy_netlify" --site="${{ secrets.NETLIFY_SITE_ID }}" --debug
